(function(g,v,M){g.execute(function(){g.when("A","a-modal").register("dmusic_webstore_prime",function(c,a){function b(a,b){b===M&&(b="track");var g=c.$("#CPToastContainer");if(!("object"!==typeof g||0>=g.length||""===a)){var e=c.$("#CPToastMessage");if(!("object"!==typeof e||0>=e.length)){var k=c.$("#CPToastMessage_"+b);"object"!==typeof k||0>=k.length||(e.html(k.html().replace("#title#",a+"<br>")),g.show(),setTimeout(function(){g.fadeOut(1E3)},2E3))}}}function I(a){"object"===typeof a&&"object"===
typeof a.button&&(a.button.addClass("aok-hidden"),a.button.siblings().removeClass("aok-hidden"),a.button.siblings("#PrimeUpsellInstruction").addClass("aok-hidden"),a.status=1)}function A(){var b=a.get(c.$("#cross_fulfillment_modal"));b.lock().show();c.$("#cross_fulfillment_close_button").click(function(){b.unlock().hide()});c.$("#cross_fulfillment_fix_button").click(function(){b.unlock().hide();v.location="https://"+v.location.hostname+"/gp/dmusic/account/settings/ref=dm_rw_pp_kcf_fix"});return!1}
var y={modalElm:null,popup:function(b){this.modalElm=a.create("<span>",{activate:"onclick",closeButton:!1,dataStrategy:"ajax",name:"touModal",url:"/gp/dmusic/modalPurchasing/touModal?ASIN="+b,width:500});this.modalElm.lock(20).show()},close:function(){this.modalElm&&(this.modalElm.unlock(20),a.remove(this.modalElm))}},E={recordAddPrimeContent:function(a){var b={};"playlist"!==a.type&&(b.appVersion="1.0.0",b.isPrimeMusic="true",b.baseEventVersion=1,b.specificEventVersion=1,b.actionName="clickedAddPrimeContent",
b.linkType=a.type.toUpperCase(),b.asin=a.asin,b.resourceType="STORE",b.source="WIFI",b.pageType="Detail",b.selectionSourceType="track"===a.type?a.source:"",b.selectionSourceId="track"===a.type?a.sourceId:"",c.$.post("/gp/dmusic/utility/metrics-mts.html",b))}},r=function(a){if("object"===typeof a){this.button=a;this.status=0;var b=a.find("button");0===b.length&&(b=a.find("a"));0===b.length&&(b=a);this.asin=b.attr("data-asin");this.parentAsin=b.attr("data-parentAsin");this.csrf_session=b.attr("data-session");
this.type=b.attr("data-type")?b.attr("data-type"):"track";this.callback=b.attr("data-callback");this.title=b.attr("data-title")?b.attr("data-title"):"The "+this.type;this.client=b.attr("data-client")?b.attr("data-client"):"dm_dp";this.source="search"===this.client?"SEARCH":b.attr("data-source");this.sourceId=b.attr("data-sourceId");this.ref=b.attr("data-ref")?b.attr("data-ref"):"dm_ws_xx_xx_xx_aart_xx_xx";this.legacyMTS=b.attr("data-legacyMTS");a=b.attr("data-autoAdd");1!==a&&"1"!==a||this.addToLib()}},
t={buttonHash:{},parentHash:{},add:function(a){for(var b=0,g=a.length;b<g;++b){var e=new r(c.$(a[b]));this.buttonHash[e.asin]||(this.buttonHash[e.asin]=[]);this.buttonHash[e.asin].push(e);"track"===e.type&&"string"===typeof e.parentAsin&&(this.parentHash[e.parentAsin]||(this.parentHash[e.parentAsin]=[]),this.parentHash[e.parentAsin].push(e))}b=function(a){var b=(new r(c.$(this))).addToLib();b&&a.preventDefault();return!b};c.$.isFunction(a.live)?a.live("click",b):a.click(b)},register:function(){this.add(c.$(".robinAddButton:not(.CloudPlayerDirectLink)"))}};
r.prototype.addToLib=function(){if(this.asin===M||this.csrf_session===M)return!1;var a="playlist"===this.type?"/gp/dmusic/playlist/utility/follow_playlist.html/ref="+this.ref:"/gp/dmusic/buyBox/utility/add_to_library.html/ref="+this.ref,h="asin="+this.asin+"&sessionid="+this.csrf_session+"&acceptsTOU="+(1===this.acceptsTOU||"1"===this.acceptsTOU?1:0);"playlist"!==this.type||1!==this.acceptedTOU&&"1"!==this.acceptedTOU||(h+="&acceptedTOU=1");var g=this;c.$.ajax({url:a,data:h,success:function(a){var c=
a.status;if((0===c||"0"===c)&&a.hasOwnProperty("exception")){if("AccountNotVerifiedException"===a.exception){a="/gp/dmusic/verification/addCreditCardMP3?robinPath=1&asin.0="+g.asin;a+="&returnUrl="+encodeURIComponent(v.location);v.location=a;return}if("InvalidTermsOfUseException"===a.exception){if("search"===g.client){location.href="/gp/product/"+g.asin+"/ref=dm_s_rb?autoAdd=1";return}y.popup(g.asin);return}if("CrossMarketplaceCloudPlayerHomeException"===a.exception){A();return}}if(1===a.status||
"1"===a.status)"string"===typeof g.title&&0<g.title.length&&b(g.title,g.type),E.recordAddPrimeContent(g);"string"===typeof g.callback&&(c=v[g.callback],"function"===typeof c&&c(a,g))},error:function(a){console.log("ERROR: could not add to library")},dataType:"json",type:"POST",async:1,timeout:5E3});return!0};g.when("dmusic_webstore_app_upsell").execute(function(a){c.$.ajax({url:"/gp/dmusic/modalPurchasing/utility/is-appupsell-eligible.html",cache:!1,success:function(b){1===b.isAppUpsellEligible&&
(a.AppUpsell.modal.shouldShow=!0)},error:function(a){}})});return{DigitalMusicRobinBtnManager:t,DigitalMusicRobinMetrics:E,DigitalMusicTOUModal:y,robinToggleToPlayButton:function(a,b){if("object"===typeof a&&a.hasOwnProperty("status")&&"object"===typeof b){var c=a.status;if(1===c||"1"===c){if("object"===typeof b.button)if("object"===typeof t){c=t.buttonHash;if("object"===typeof c){var e=t.buttonHash[b.asin];if("object"===typeof e)for(var k=0;k<e.length;++k)"object"===typeof e[k]&&I(e[k]);else I(b)}e=
t.parentHash;if("object"===typeof e)if("album"===b.type){if(c=e[b.asin],"object"===typeof c)for(var d in c)"object"===typeof c[d]&&I(c[d])}else if("track"===b.type&&"string"===typeof b.parentAsin)if(e=e[b.parentAsin],"object"===typeof e){k=!0;for(d in e)if("object"===typeof e[d]&&(0===e[d].status||"0"===e[d])){k=!1;break}if(k&&"object"===typeof c&&(c=t.buttonHash[b.parentAsin],"object"===typeof c))for(d in c)"object"===typeof c[d]&&I(c[d])}else I(b)}else I(b);e=navigator.userAgent;d=-1!==e.indexOf("MSIE");
c=-1!==e.indexOf("Trident");e=-1!==e.indexOf("Edge");d||c||e||g.when("dmusic_webstore_app_upsell").execute(function(a){a=a.AppUpsell.modal;a.shouldShow&&(a.show(),a.shouldShow=!1)})}}},digitalMusicAddToLibByAsin:function(a,b){if("object"===typeof t&&"object"===typeof t.buttonHash){var c=t.buttonHash[a];if("object"===typeof c&&0<c.length){if(1===b||"1"===b)c[0].acceptsTOU=1;c[0].addToLib()}}}}})})})(function(){var g=window.AmazonUIPageJS||window.P,v=g._namespace||g.attributeErrors;return v?v("DigitalMusicWebsitePrimeAssets"):
g}(),window);