(function(d,v){d.execute(function(){d.when("A","jQuery","atf").execute(function(g,a){if(a("#bookDescription_feature_div").length){var b=a("#outer_postBodyPS").height();a("#postBodyPS").height()>b+30?(a("#outer_postBodyPS").show(),a("#outer_postBodyPS").css("height",b),a("#psPlaceHolder").show(),a("#expandPS").show(),a("#collapsePS").hide()):(a("#outer_postBodyPS").css("height","auto"),a("#psPlaceHolder").hide());a("#bookDescription_feature_div .a-link-expander").click(function(){a("#bdSeeAllPrompt").is(":hidden")?
(a("#outer_postBodyPS").animate({height:b},500),a("#bdSeeAllPrompt").show(),a("#bdSeeLessPrompt").hide()):(a("#outer_postBodyPS").animate({height:a("#postBodyPS").height()},500),a("#bdSeeAllPrompt").hide(),a("#bdSeeLessPrompt").show());a("#bdExpanderIcon").toggleClass("rotate");return!1})}});d.when("A","jQuery","DynamicIframe","bookDescriptionIframe").execute(function(g,a,b,c){if(a("#bookDescription_feature_div").length){var n=null,g=c.encodedDescription,s=0,d={},E=c.iFrameId,B=function(){var b=a("#"+
E).contentDocument;if(c.staticHeight&&b&&b.defaultView)var g=parseInt(c.numLines,10),d=b.find("#iframeContent"),b=b.defaultView.getComputedStyle(d,null).getPropertyValue("line-height"),b=parseFloat(b),b=Math.round(b*g);else g=document.getElementById(c.featureDiv).offsetTop,b=document.getElementById(c.imageBlockDiv).offsetTop,d=document.getElementById(c.imageBlockDiv).offsetHeight,b=b+d-g-30,b<112&&(b=112);g=document.getElementById(c.postBodyId).offsetHeight;g>b+30?a("#"+c.seeLessPromptId).hasClass("a-hidden")?
(a("#"+c.outerBodyId).height(b),a("#"+c.placeHolderId).removeClass("a-hidden"),a("#"+c.seeAllPromptId).removeClass("a-hidden")):a("#"+c.outerBodyId).height(g):(a("#"+c.outerBodyId).height(g),a("#"+c.placeHolderId).addClass("a-hidden"),a("#"+c.seeAllPromptId).removeClass("a-hidden"),a("#"+c.seeLessPromptId).addClass("a-hidden"),a("#"+c.expanderIconId).removeClass("rotate"));b=a("#"+c.outerBodyId).height();s==0&&(s=b);b=s;g>b+30&&a("#"+c.seeLessPromptId).is(":hidden")?(a("#"+c.outerBodyId).show(),a("#"+
c.outerBodyId).css("height",b),a("#"+c.placeHolderId).show(),a("#expandPS").removeClass("a-hidden"),a("#collapsePS").addClass("a-hidden")):a("#"+c.outerBodyId).css("height","auto")};d.iframeId=E;d.iframeWrapperId="bookDesc_iframe_wrapper";d.overriddenCSSId="bookDesc_override_CSS";d.encodedIframeContent=g;d.initialResizeCallback=B;n=new b(d);n.createIframe();typeof n!=="undefined"&&n instanceof b&&(a(v).resize(function(){n.resizeIframe(B)}),a(v).bind("imageResize",function(){n.resizeIframe(B)}));a("#"+
c.featureDiv+" .a-link-expander").click(function(){var b="#"+c.outerBodyId,g="#"+c.seeAllPromptId,d="#"+c.seeLessPromptId,n="#"+c.expanderIconId,r="#"+c.postBodyId;a(g).hasClass("a-hidden")?(r=s,a(b).animate({height:r},500),a(g).removeClass("a-hidden"),a(d).addClass("a-hidden"),a(n).removeClass("rotate")):(a(b).animate({height:a(r).height()},500),a(g).addClass("a-hidden"),a(d).removeClass("a-hidden"),a(n).addClass("rotate"));return!1})}});d.when("A","jQuery","ImageBlockATF","SampleAudioPlayer","cf").execute(function(g,
a,b,c){function n(){var a=v.innerWidth||document.body.offsetWidth;if(!(a<=0))if(a>b.windowWidthThreshold&&t.width()<=b.configWidths[0]){var a=b.configWidths[1],e=a/b.holderRatio,c=b.frontImageWidth,g=b.frontImageHeight;s(a,e,c,g)}else a<b.windowWidthThreshold&&t.width()>b.configWidths[0]&&(a=b.configWidths[0],e=a/b.holderRatio,b.frontImageAspectRatio>b.holderRatio?(c=a,g=c/b.frontImageAspectRatio):(g=e,c=g*b.frontImageAspectRatio),s(a,e,c,g))}function s(e,c,g,C){if(e>0&&c>0&&g>0&&C>0){T.css("margin-left",
e+b.centerColMargin).removeClass("centerColumn");x.css("width",e);var d=c+b.containerMargin+b.flipLinkMinHeight;t.css("width",e).css("height",d);S(g,C);y.css("height",c-(c-i.outerHeight())/2);e=(y.outerWidth()-i.outerWidth())/2;c=y.outerHeight()-i.outerHeight();j.css("top",c).css("left",e);u.css("top",c+P).css("left",e+g-u.width());a(this).trigger("imageResize");z&&z.hide()}}function S(a,b){i.css("width",a).css("height",b);var e=i.width(),c=i.height();j.css("width",e).css("height",c);typeof l!=="undefined"&&
l.length>0&&(l.css("width",e).css("height",c),k.css("height",c),I&&O&&(c=k.width(),o=(e-c)/2-2,k.removeClass("ieTransition").css("left",(e-c)/2),f=="front"?k.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+o+"px)"):k.css("transform","perspective(3000px) rotateY(90deg) translateZ("+o+"px)"),g.delay(function(){k.addClass("ieTransition")},10)))}function E(){var a=q.find(".audioSamplePopover");d.when("jQuery","a-popover","ready").execute(function(b,e){z=e.create(U,{activate:"onclick",
position:"triggerRight",inlineContent:a})});C.click(B)}function B(){z&&z.show()}function G(a){a.bind("audioEnded",function(){J.hide();K.hide();C.show();e=0;z&&z.hide()});a.bind("audioPlaying",function(){J.hide();C.hide();K.show();e=1;B()});a.bind("audioPaused",function(){K.hide();C.hide();J.show();e=0;z&&z.hide()})}function M(){e?D.pause():D.play()}function H(){if(typeof SitbReader!="undefined")if(f=="back"&&SitbReader.currentBook&&SitbReader.currentBook.bookmarks){var a=SitbReader.currentBook.bookmarks.getFirstAndLastPageNumberByName("Back Cover").first,
e=SitbReader.currentBook.bookmarks.getFirstAndLastPageNumberByName("Back Flap").first;a?SitbReader.LightboxActions.openReaderToPage(a):e?SitbReader.LightboxActions.openReaderToPage(e):SitbReader.LightboxActions.openReader(b.litbData.litbReftag)}else SitbReader.LightboxActions.openReader(b.litbData.litbReftag)}function N(a){O?a.type=="click"?f=="front"?(f="back",i.removeClass("frontUnrotated frontUnrotatedHover").addClass("frontRotated"),l.removeClass("backUnrotated backUnrotatedHover").addClass("backRotated"),
k.css("transform","perspective(3000px) rotateY(90deg) translateZ("+o+"px)"),h.addClass("a-hidden"),p.removeClass("a-hidden"),L.addClass("flipToBackImgRotate")):(f="front",i.removeClass("frontRotated frontRotatedHover").addClass("frontUnrotated"),l.removeClass("backRotated backRotatedHover").addClass("backUnrotated"),k.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+o+"px)"),p.addClass("a-hidden"),h.removeClass("a-hidden"),L.removeClass("flipToBackImgRotate")):a.type=="mouseenter"?
f=="front"?(i.removeClass("frontUnrotated").addClass("frontUnrotatedHover"),l.removeClass("backUnrotated").addClass("backUnrotatedHover"),k.css("transform","perspective(3000px) rotateY(-55deg) translateZ("+o+"px)")):(i.removeClass("frontRotated").addClass("frontRotatedHover"),l.removeClass("backRotated").addClass("backRotatedHover"),k.css("transform","perspective(3000px) rotateY(80deg) translateZ("+o+"px)")):f=="front"?(i.removeClass("frontUnrotatedHover").addClass("frontUnrotated"),l.removeClass("backUnrotatedHover").addClass("backUnrotated"),
k.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+o+"px)")):(i.removeClass("frontRotatedHover").addClass("frontRotated"),l.removeClass("backRotatedHover").addClass("backRotated"),k.css("transform","perspective(3000px) rotateY(90deg) translateZ("+o+"px)")):a.type=="click"?f=="front"?(j.removeClass("bookCanvasTransformHover").addClass("rotated"),h.addClass("a-hidden"),p.removeClass("a-hidden"),L.addClass("flipToBackImgRotate"),f="back"):(j.removeClass("rotated rotatedHover"),p.addClass("a-hidden"),
h.removeClass("a-hidden"),L.removeClass("flipToBackImgRotate"),f="front"):a.type=="mouseenter"?f=="front"?j.addClass("bookCanvasTransformHover"):j.removeClass("rotated").addClass("rotatedHover"):f=="front"?j.removeClass("bookCanvasTransformHover"):j.removeClass("rotatedHover").addClass("rotated")}function r(){A.addClass("parentImage");k.addClass("bookSpine").removeClass("a-hidden");j.addClass("bookCanvasTransition");i.addClass("bookFrontTransition");g.delay(function(){j.addClass("bookCanvasTransformHover");
g.delay(function(){j.removeClass("bookCanvasTransformHover")},1500)},50)}function F(){var a=k.outerWidth(),b=i.outerWidth();o=(b-a)/2-2;k.css("left",(b-a)/2).css("transform","perspective(3000px) rotateY(-90deg) translateZ("+o+"px)");i.addClass("ieTransition ieBookShadow").css("transform-origin","50% 50% -"+a/2+"px");l.addClass("ieTransition backLanding ieBookShadow").removeClass("a-hidden").css("transform-origin","50% 50% -"+a/2+"px");k.addClass("ieTransition ieBookShadow").removeClass("a-hidden").css("transform-origin",
"50% 50% -"+a/2+"px");g.delay(function(){l.removeClass("backLanding").addClass("backUnrotated");i.addClass("frontUnrotated");k.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+o+"px)")},50);i.mouseenter(function(){k.css("transform","perspective(3000px) rotateY(-75deg) translateZ("+o+"px)")});i.mouseleave(function(){k.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+o+"px)")});m.removeClass("a-hidden")}var t=a("#imageBlock"),A=t.find("#img-wrapper"),y=t.find("#imageBlockContainer"),
j=t.find("#img-canvas"),l=j.find(".backImage"),k=j.find(".sideImage"),i=j.find(".frontImage"),u=a("#imageBlockOuter").find("#sitbLogo"),m=t.find(".flipImageToBack"),q=t.find(".sampleBookAudio"),w=0,f="front",I=0,e=0,C=q.find(".audioListenText"),K=q.find(".audioPlayingText"),J=q.find(".audioPausedText"),Q=q.find(".audioText"),U=q.find(".audioPopoverTrigger"),D,h=m.find(".flipToBackText"),p=m.find(".flipToFrontText"),L=m.find(".flipToBackImg"),O=a.browser.msie||!!navigator.userAgent.match(/Trident/),
z,x=a("#leftCol"),T=a("#centerCol"),o=0,R=a("#imageBlockOuter").find("#sitbLogoImg"),P=parseInt(t.css("margin-top"));(function(){var e=A.offset(),d=i.offset(),f=d.top-e.top,e=d.left-e.left,d=i.outerWidth(),x=i.outerHeight(),h=A.outerHeight()-(A.outerHeight()-i.outerHeight())/2,o=k.outerWidth();A.css("position","relative");u.css("top",f+P).css("left",e+d-u.width());j.css("position","absolute").css("top",f).css("left",e).css("width",d).css("height",x);i.css("position","absolute").css("top","0").css("left",
"0");l.css("position","absolute").css("top","0").css("left","0");k.css("position","absolute").css("top","0").css("left","-"+o+"px");y.css("height",h);if(b.audibleData&&b.audibleData.audioSampleSrc)D=new c,f={},f.audioSrc=b.audibleData.audioSampleSrc,f.audioId="img-blk-audio-sample",f.audioControllerId=q,f.flashPlayerUrl=b.audibleData.flashPlayerUrl,f.bindEventsCallback=G,D.init(f);d=1;f=["Perspective","TransformStyle","TransformOrigin","BackfaceVisibility","Transition"];for(e=0;e<f.length;e++)if(d){for(var d=
f[e],x=["Webkit","Moz","O","ms"],h=document.createElement("div"),o=!1,p=0;p<x.length;p++)x[p]+d in h.style&&(o=o||!0);if(d==="Perspective"&&"WebkitPerspective"in h.style)o=!1,h.id="test3d",document.body.appendChild(h),h.offsetHeight===3&&(o=!0),h.parentNode.removeChild(h);d=o}(I=(w=d)&&typeof l!=="undefined"&&l.length>0)?(f=i.width(),e=i.height(),f>0&&e>0&&(j.addClass("image-3d"),l.css("width",f).css("height",e),k.css("height",e),O?F():(r(),l.addClass("bookBack").removeClass("a-hidden"),m.removeClass("a-hidden")),
D&&D.isPlayerAvailable?m.addClass("a-span6"):m.addClass("a-span12"),g.declarative("flip-action",["click","mouseenter","mouseleave"],N))):j.addClass("image-2d");b&&b.litbData&&b.litbData.hasLitb&&b.litbData.litbReftag&&(R.removeClass("a-hidden"),R.click(H),j.click(H));D&&D.isPlayerAvailable&&(I?q.addClass("a-span6"):q.addClass("a-span12"),K.hide(),J.hide(),q.removeClass("a-hidden"),Q.children().click(M),f=parseInt,e=C.outerWidth(),d=K.outerWidth(),x=J.outerWidth(),h=0,e>0&&d>0&&x>0&&(h=Math.max(e,
d,x)+5),(f=f(h))&&f>0&&Q.css("width",f),E());b.disableResize||a(v).resize(n)})()});d.when("A","jQuery","ImageBlockATF","ImageGalleryMarkup").execute(function(d,a,b){function c(){var a=b.imageGalleryData;if(a&&a.length>0){m={};q=a.length;for(var c=0;c<a.length;c++)m["ig-thumb-"+c]=a[c]}}function n(){u=F.height();t.length>0&&(u-=t.height());if(a.browser.msie&&a.browser.version==7){var e=A.outerHeight()-A.height();e&&e>0&&(u-=e)}if(u&&u>0){A.css("height",u);var e=k.height(),b=k.width();y.css("height",
e).css("width",b).data("height",e).data("width",b)}}function s(){if(F.length>0){n();E();if(q>0)for(var e=0;e<q;e++){var b="ig-thumb-"+e,b=a('<div class="ig-thumb-image"><img class="ig-thumb-inner '+(b==f?"selected":"")+'" id="'+b+'" src="'+m[b].thumbUrl+'"></div>');l.append(b)}zoomOptions=G();w.setImageData(zoomOptions);w.attachZoomEvents()}}function v(){var a=m[f].dimensions[0],b=m[f].dimensions[1];j.css("max-width",a).css("max-height",b).removeClass("image-stretch-horizontal image-stretch-vertical");
j.addClass(B(a,b))}function E(){m[f]&&(v(),j.attr("src",m[f].mainUrl))}function B(a,b){var c=y.data("width")/y.data("height"),d="image-stretch-vertical";a/b>c&&(d="image-stretch-horizontal");return d}function G(){var a={};if(m[f])a.containerId="igInner",a.imageId="igImage",a.imageWidth=m[f].dimensions[0],a.imageHeight=m[f].dimensions[1];return a}function M(){m&&l.find(".ig-thumb-inner").click(function(){var b=this.id,c=a(this),d=m[b];if(!c.hasClass("selected")&&d)f=b,l.find(".selected").removeClass("selected"),
c.addClass("selected"),w.detachEvents(),j.addClass("a-hidden"),i.show(),document.getElementById("igImage").onload=I,E(),b=G(),w.setImageData(b)})}function H(){var a=d.viewport();r.closest(".a-popover-modal").css("width",a.width*0.75).css("height",a.height*0.75);n();w.detachEvents();v();a=G();w.setImageData(a);w.attachZoomEvents()}function N(){d.capabilities.orientation&&(d.on("orientationchange",function(){H()}),d.on("a:popover:afterHide:imageGallery",function(){d.off("a:popover:afterHide:imageGallery");
d.on("a:popover:beforeShow:imageGallery",function(){H()})}))}var r=a("#imgGalleryContent"),F=r.closest(".a-popover-wrapper"),t=F.find(".a-popover-header"),A=F.find(".a-popover-inner"),y=r.find("#igInner"),j=y.find("#igImage"),l=r.find(".ig-thumbs"),k=r.find(".ig-main-image"),i=r.find(".loading-bar"),u=0,m=null,q=0,w=new function(){function b(){p.bind("touchstart.ig touchmove.ig",function(a){c(a);p.unbind("touchstart.ig touchmove.ig");p.bind("touchmove.ig",function(a){c(a)});p.bind("touchend.ig",function(){f.zoomOut();
p.unbind("touchstart.ig touchmove.ig touchend.ig");b()})})}function c(a){q&&a.preventDefault();var b,d={},e=h.width(),g=h.height();b=a.pageX-h.offset().left;a=a.pageY-h.offset().top;d.x=m?b*j/e-b:0;d.y=n?a*l/g-a:0;f.zoomIn(d)}var f={},i=null,k=null,j=0,l=0,h=null,p=null,m=!1,n=!1,q=d.capabilities.touch;f.setImageData=function(b){i=b.containerId;k=b.imageId;j=b.imageWidth;l=b.imageHeight;h=a("#"+i);p=a("#"+k);m=j>0&&h.length>0&&j>h.width();n=l>0&&h.length>0&&l>h.height()};f.attachZoomEvents=function(){if(m||
n)h.addClass("zoomable"),q?b():p.click(function(a){h.hasClass("zoomed-in")?(f.zoomOut(),p.unbind("mousemove")):h.hasClass("zoomed-out")&&(c(a),p.mousemove(function(a){c(a)}))})};f.zoomIn=function(a){p.css("top",-1*a.y);p.css("left",-1*a.x);h.removeClass("zoomed-out").addClass("zoomed-in")};f.zoomOut=function(){h.removeClass("zoomed-in").addClass("zoomed-out");p.css("top","auto").css("left","auto")};f.detachEvents=function(){f.zoomOut();p.unbind();h.removeClass("zoomable")};return f},f;r.length>0&&
(f="ig-thumb-0",i.hide(),c(),s(),M(),N());var I=function(){i.hide();j.removeClass("a-hidden");w.attachZoomEvents()}});d.when("A","jQuery").execute(function(d,a){if(a("#imageBlockThumbs").length){var b=function(){var b=a("#imgThumbs"),n=b.data("a-modal"),s=d.viewport();n.width=s.width*0.75;n.height=s.height*0.75;b.data("a-modal",n)};b();d.on("resize",b)}})})})(function(){var d=window.AmazonUIPageJS||window.P,v=d._namespace||d.attributeErrors;return v?v("MSXBooksDetailPageAsset"):d}(),window);
/* ******** */
(function(r,z,R){r.execute(function(){r.when("A","jQuery","atf").execute(function(r,d,g){var m=d("#rbbContainer");m.find(".rbbHeaderLink").attr("href","javascript:void(0);");m.find(".rbbHeader .displayNone i.prime").hide();m.find(".rbbHeader .displayNone .primeBadge").hide();m.find(".rbbHeader .ubbPrimeBadge").hide();m.find(".rbbHeader .prime-plus-price").hide();m.find(".rbbHeader .displayNone").removeClass("displayNone");d("#rbbContainer .rbbSection.unselected .dp-accordion-inner").hide();var b=
d("#buyDealSection").length;d("#rbbContainer .rbbSection .rbbHeader").click(function(a){d(a.target);a=d(this);a=a.hasClass("rbbHeader")?a:a.parents(".rbbHeader");if(a.parents(".rbbSection").hasClass("selected"))return!1;m.find(".selected .a-icon-radio-active").removeClass("a-icon-radio-active").addClass("a-icon-radio-inactive");m.find(".selected .offer-price").removeClass("a-color-price a-size-medium").addClass("a-color-base a-size-base");m.find("i.a-icon.prime").hide();m.find(".primeBadge").hide();
m.find(".ubbPrimeBadge").hide();var c=m.find(".prime-plus-price-grid");c.hasClass("hidden")?c.removeClass("hidden").show():c.addClass("hidden").hide();m.find(".prime-plus-price").show();a.parents(".rbbSection").removeClass("unselected").addClass("selected");a.parents(".rbbSection").toggleClass("dp-accordion-active",500);a.find(".a-icon-radio-inactive").removeClass("a-icon-radio-inactive").addClass("a-icon-radio-active");a.find(".offer-price").removeClass("a-color-base a-size-base").addClass("a-color-price a-size-medium");
a.find("i.a-icon.prime").show();a.find(".primeBadge").show();a.find(".prime-plus-price").hide();d("#rbbContainer .rbbSection .rbbContent").find(".offer-price").removeClass("a-color-base").addClass("a-color-price");a.find(".ubbPrimeBadge").show();var e=d(this).attr("id"),f,g;m.find(".rbbSection").each(function(a,b){d(b).find(".rbbHeader")[0].id==e?f=d(b):d(b).hasClass("selected")&&(g=d(b))});g.find(".rbbContent").slideUp(500,function(){g.removeClass("selected").addClass("unselected");g.toggleClass("dp-accordion-active",
500)});f.find(".rbbContent").slideDown(500);d.browser.msie&&7==parseInt(d.browser.version,10)&&(f.find(".rbbContent").css("display","inline"),setTimeout(function(){f.find(".rbbContent").css("display","block")},505));if(b&&"undefined"!=typeof UDPDealView)if(d("#gbld_header_message").show(),"buyDealSection"==e)UDPDealView.prototype.onSelectLDBuybox();else UDPDealView.prototype.onSelectRegularBuybox();return!0})});r.when("A","jQuery").execute(function(r,d){d("#one-click-button-ubb, #usedbuyBox #add-to-cart-button-ubb").click(function(){var g=
d("#addToCart"),m=g.attr("action").replace("ref=dp_start-bbf_1_glance","ref=dp_start-ubbf_1_glance");g.attr("action",m);return!0});amznJQ.available("popover",function(){d("#usedItemConditionInfoLink").amazonPopoverTrigger({showCloseButton:!1,closeEventInclude:["CLICK_TRIGGER","CLICK_OUTSIDE","MOUSE_LEAVE"],locationElement:d("#usedItemConditionInfoLink"),location:"bottom",width:250,localContent:"#usedItemConditionInfoPopover"})})})})})(function(){var r=window.AmazonUIPageJS||window.P,z=r._namespace||
r.attributeErrors;return z?z("OffersBooksDetailPageAsset"):r}(),window);
/* ******** */
(function(r,z,R){r.execute(function(){r.when("A","jQuery","atf").execute(function(M,d,g){var m,b=0;r.when("DPClientLogger").execute(function(){"undefined"!=typeof z.DPClientLogger&&(m=new z.DPClientLogger.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))});d("#bookDetails_feature_div .hero-more").click(function(a){a.preventDefault();a=d(this).attr("data-popupID");var c=d("#"+a),e=d(this).offset().left+d(this).width()/2,f=d("#popupContent").offset().left,e=(e-f)/d("#popupContent").width()*100;
d("#"+a+" .pointer").css({left:e+"%"});d("#popupContent .details-popup").filter(":visible").length?d("#popupContent .details-popup").filter(":visible").attr("id")!==a?(d("#popupContent .details-popup").filter(":visible").slideToggle(300),c.slideToggle(300)):c.slideUp(300):(c.slideDown(300),d(this).hasClass("hero-more")&&d("html,body").animate({scrollTop:d("#bookDetails_feature_div").offset().top-50},600));m&&!b&&(m.logImpression("ma-books-br-details"),b=1)});d("#bookDetails_feature_div .moreNarratorLink").click(function(){if(location.pathname.replace(/^\//,
"")==this.pathname.replace(/^\//,"")||location.hostname==this.hostname){var a=d(this.hash),a=a.length?a:d("[name="+this.hash.slice(1)+"]");a.length&&d("html,body").animate({scrollTop:a.offset().top},1E3);return!1}});d("#bookDetails_feature_div .details-popup button").click(function(a){d(this).parent().slideUp(300)})});r.when("A","jQuery","atf").execute(function(r,d,g){function m(){var b=parseInt(d("#byline").width()),a=0;d("#byline .author").each(function(){d(this).is(".notFaded")&&(a+=d(this).outerWidth())});
a+=d("#byline .more").outerWidth();if(a>b){var c=d("#byline .author.notFaded").length;d(d("#byline .author.notFaded").get().reverse()).each(function(e){a>b&&e<c-1&&(e=d(this).width(),d(this).removeClass("notFaded"),d(this).fadeOut(10,function(){d(this).hide()}),a-=e,d("#byline .moreCount").html(d("#byline .author").length-d("#byline .author.notFaded").length),d("#byline .more").addClass("notFaded").fadeIn(10))})}else if(a<b&&d("#byline .author.notFaded").length<d("#byline .author").length){var e=
b-a;d("#byline .author").each(function(){if(!d(this).hasClass("notFaded")){var a=d(this).outerWidth();a<=e?(e-=a,d(this).addClass("notFaded").fadeIn(10),a=d("#byline .author").length-d("#byline .author.notFaded").length,0===a?d("#byline .more").removeClass("notFaded").fadeOut(10):(d("#byline .moreCount").html(a),d("#byline .more").addClass("notFaded").fadeIn(10))):e=0}})}}d("#byline .showMoreLink").click(function(){d("#byline .author").each(function(){d(this).hasClass("notFaded")||d(this).addClass("notFaded").fadeIn(0);
d("#byline .more").removeClass("notFaded").fadeOut(0)});return!1});d("#byline .contributorNameID").mouseenter(function(){var b=d(this).attr("data-asin"),a={},c="isAjaxComplete_"+b,e="isAjaxInProgress_"+b,f=r.state("popoverImage-state");a.entityID=b;"1"!==f[c]&&"1"!==f[e]&&(d.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:a,dataType:"html",timeout:1E3,success:function(a){d("#contributorImageContainer"+b).get(0).innerHTML=a;f[c]="1";r.state("popoverImage-state",
f)},error:function(){f[e]="0";r.state("popoverImage-state",f)}}),f[e]="1",r.state("popoverImage-state",f))});(function(b){var a=parseInt(b.width()),c=parseInt(b.find(".more").outerWidth()),e=0;d("#byline .author").each(function(){d(this).is(".notFaded")&&(e+=d(this).outerWidth())});d("#byline .more").attr("data-width",c);var f=a-c;if(f>e)b.find(".author").each(function(){var a=d(this).index();3<=parseInt(a)?(a=d(this).outerWidth(),d(this).attr("data-width",a),a<f?(f-=a,d(this).addClass("notFaded"),
d(this).fadeIn("slow")):(f=0,d(this).fadeOut("slow"))):(a=d(this).outerWidth(),d(this).attr("data-width",a),f-=a)});else{var g=d("#byline .author.notFaded").length;d(d("#byline .author.notFaded").get().reverse()).each(function(a){f<e&&a<g-1&&(a=d(this).outerWidth(),e-=a,d(this).fadeOut("slow").removeClass("notFaded"))})}a=b.find(".author").length-b.find(".author.notFaded").length;0<a&&(b.find(".moreCount").html(a),b.find(".more").fadeIn("slow"),b.find(".more").addClass("notFaded"))})(r.$("#byline"));
d(z).resize(function(){m()})});r.when("A","jQuery","DynamicIframe","ProductDescriptionData","cf").execute(function(r,d,g,m){function b(){n=0;var a=Math.min(k,l.length);c(0,a)}function a(){0<t.length&&0<z.length&&(x="collapsed",t.removeClass("a-hidden"),t.click(function(){"collapsed"===x?(p?z.animate({height:"show"}):(z.removeClass("extraReviews"),c(n,l.length),p=1),t.removeClass("collapsed").addClass("expanded"),x="expanded"):(z.animate({height:"hide"}),t.removeClass("expanded").addClass("collapsed"),
x="collapsed")}))}function c(a,b){var c;for(c=a;c<b;c++){var f={};f.iframeId="er_iframe_"+c;f.iframeWrapperId="er_iframe_wrapper_"+c;f.iframeContainerId="er_container_"+c;f.iframeExpanderId="er_expander_"+c;f.iframeColumnId="er_column_"+c;var k=f,m=l[c],p="<h3 class='erSource'>"+m.source+"</h3><div class='erContent'>"+m.content+"</div>";m.footnote&&(p=p+"<em class='erFootnote'>"+m.footnote+"</em>");k.encodedIframeContent=p;f.initialResizeCallback=e;k=f;m={};m.id=d("#"+k.iframeId);m.column=d("#"+k.iframeColumnId);
m.wrapper=d("#"+k.iframeWrapperId);m.container=d("#"+k.iframeContainerId);m.expander=d("#"+k.iframeExpanderId);m.iframeObj=new g(k);m.state="full";k=m;q[f.iframeId]=k;k.column.removeClass("extraReviews");k&&"undefined"!=typeof k.iframeObj&&"function"==typeof k.iframeObj.createIframe&&k.iframeObj.createIframe();h(k);n++}}function e(a){(a=q[a])&&170<a.wrapper.outerHeight()&&(a.container.css("height",140),a.expander.removeClass("a-hidden expanded").addClass("collapsed"),a.state="partial")}function f(a){(a=
q[a])&&"full"===a.state&&a.container.css("height",a.wrapper.outerHeight())}function h(a){if(a&&"undefined"!=typeof a.iframeObj&&"function"==typeof a.iframeObj.resizeIframe)r.on("resize",function(){a.iframeObj.resizeIframe(f)});a&&a.expander&&a.expander.click(function(){"partial"===a.state?(a.container.animate({height:a.wrapper.outerHeight()}),a.expander.removeClass("collapsed").addClass("expanded"),a.state="full"):(a.container.animate({height:140}),a.expander.removeClass("expanded").addClass("collapsed"),
d("html, body").animate({scrollTop:a.container.offset().top-20}),a.state="partial")})}var l=m.encodedReviews,k=parseInt(m.reviewsPerRow),n=0,p=0;m=d("#productDescription-multiColumn");var q={},t,z,x;0<m.length&&l&&0<l.length&&k&&(t=m.find(".reviewsExpander"),z=m.find(".seeMoreProductReviews"),b(),a())})})})(function(){var r=window.AmazonUIPageJS||window.P,z=r._namespace||r.attributeErrors;return z?z("PInfoBooksDetailPageAsset"):r}(),window);
/* ******** */
(function(r,z,R){r.execute(function(){r.when("A","jQuery","swfobject").register("SampleAudioPlayer",function(r,d,g){function m(a){function b(){l.audioId.trigger("audioEnded")}function e(){l.audioId.trigger("audioPlaying")}function f(){l.audioId.trigger("audioPaused")}function g(){l.audioId.trigger("audioReady")}var l={initializePlayer:function(a){l.options=a;l.isFirstPlay=1},play:function(){if(l.isFirstPlay){var k=l.options,n=d('<audio id="'+k.audioId+'" src="'+k.audioSrc+'"></audio>');k.audioControllerId.append(n);
l.audioObj=d("#"+k.audioId).get(0);l.audioId=d("#"+k.audioId);l.audioObj.addEventListener("ended",b);l.audioObj.addEventListener("playing",e);l.audioObj.addEventListener("pause",f);l.audioObj.addEventListener("loadeddata",g);"function"==typeof a.bindEventsCallback&&a.bindEventsCallback(l.audioId);l.isFirstPlay=0}l.audioObj.play()},pause:function(){l.audioObj.pause()}};return l}function b(a){var b={};z.Mp3Interface||(z.Mp3Interface={currentPlayer:null,setCurrentPlayer:function(a){a&&(Mp3Interface.currentPlayer&&
Mp3Interface.currentPlayer.audioId!==a.audioId&&(g.getObjectById(Mp3Interface.currentPlayer.audioId).stopSong(),Mp3Interface.currentPlayer.isPlaying=0),Mp3Interface.currentPlayer=a)},callback:function(a){Mp3Interface.currentPlayer&&("onPlayerInit"==a?Mp3Interface.currentPlayer.audioId.trigger("audioReady"):"onPlay"==a?(Mp3Interface.currentPlayer.audioId.trigger("audioPlaying"),Mp3Interface.currentPlayer.isPlaying=1):"onPause"==a?(Mp3Interface.currentPlayer.audioId.trigger("audioPaused"),Mp3Interface.currentPlayer.isPlaying=
0):"onComplete"==a&&(Mp3Interface.currentPlayer.audioId.trigger("audioEnded"),Mp3Interface.currentPlayer.isPlaying=0,Mp3Interface.currentPlayer.isFirstPlay=1))}});b.initializePlayer=function(a){b.isFirstPlay=1;b.options=a;Mp3Interface.setCurrentPlayer(this);a.audioControllerId.append('<div id="'+a.audioId+'"></div>');var f=a.flashPlayerUrl,h=a.audioId,l=a.minFlashVersion,k={protocol:z.location.protocol.replace(":","")};g.embedSWF(f,h,1,1,l,null,k,{allowScriptAccess:"always"});b.audioId=d("#"+a.audioId);
"function"==typeof a.bindEventsCallback&&a.bindEventsCallback(b.audioId);b.isPlaying=0};b.play=function(){b.isPlaying||(Mp3Interface.setCurrentPlayer(this),b.isFirstPlay?(g.getObjectById(b.options.audioId).playSong(a.audioSrc),b.isFirstPlay=0):g.getObjectById(b.options.audioId).pauseSong())};b.pause=function(){b.isPlaying&&(Mp3Interface.setCurrentPlayer(this),g.getObjectById(b.options.audioId).pauseSong())};return b}return function(){var a={init:function(c){if("undefined"!==typeof c.audioSrc&&"undefined"!==
typeof c.audioId&&"undefined"!==typeof c.audioControllerId){var d=c.audioSrc,f=document.createElement("audio"),h,l,d=d.match("[^.]+$");0<d.length&&(h=d[0],"mp3"==h?l="audio/mpeg":"ogg"==h?l="audio/ogg":"wav"==h&&(l="audio/wav"));h=l+'; codecs="'+h+'"';l=0;f&&f.canPlayType&&f.canPlayType(h)&&f.canPlayType(h).replace(/no/,"")&&(l=1);l?(a.player=new m(c),a.player.initializePlayer(c),a.isPlayerAvailable=1):c.flashPlayerUrl&&g&&g.hasFlashPlayerVersion("9.0.0")&&(c.minFlashVersion="9.0.0",a.player=new b(c),
a.player.initializePlayer(c),a.isPlayerAvailable=1)}},pause:function(){"undefined"!==typeof a.player&&a.player.pause()},play:function(){"undefined"!==typeof a.player&&a.player.play()}};return a}});r.register("swfobject",function(){var r=function(){function d(){if(!J){try{var a=w.getElementsByTagName("body")[0].appendChild(w.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}J=!0;for(var a=C.length,c=0;c<a;c++)C[c]()}}function g(a){J?a():C[C.length]=a}function m(a){if("undefined"!=
typeof B.addEventListener)B.addEventListener("load",a,!1);else if("undefined"!=typeof w.addEventListener)w.addEventListener("load",a,!1);else if("undefined"!=typeof B.attachEvent)q(B,"onload",a);else if("function"==typeof B.onload){var b=B.onload;B.onload=function(){b();a()}}else B.onload=a}function b(){var b=w.getElementsByTagName("body")[0],c=w.createElement("object");c.setAttribute("type","application/x-shockwave-flash");var d=b.appendChild(c);if(d){var e=0;(function(){if("undefined"!=typeof d.GetVariable){var f=
d.GetVariable("$version");f&&(f=f.split(" ")[1].split(","),I.pv=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)])}else if(10>e){e++;setTimeout(arguments.callee,10);return}b.removeChild(c);d=null;a()})()}else a()}function a(){var a=P.length;if(0<a)for(var b=0;b<a;b++){var d=P[b].id,g=P[b].callbackFn,k={success:!1,id:d};if(0<I.pv[0]){var l=p(d);if(l)if(!t(P[b].swfVersion)||I.wk&&312>I.wk)if(P[b].expressInstall&&e()){k={};k.data=P[b].expressInstall;k.width=l.getAttribute("width")||"0";k.height=
l.getAttribute("height")||"0";l.getAttribute("class")&&(k.styleclass=l.getAttribute("class"));l.getAttribute("align")&&(k.align=l.getAttribute("align"));for(var n={},l=l.getElementsByTagName("param"),m=l.length,q=0;q<m;q++)"movie"!=l[q].getAttribute("name").toLowerCase()&&(n[l[q].getAttribute("name")]=l[q].getAttribute("value"));f(k,n,d,g)}else h(l),g&&g(k);else x(d,!0),g&&(k.success=!0,k.ref=c(d),g(k))}else x(d,!0),g&&((d=c(d))&&"undefined"!=typeof d.SetVariable&&(k.success=!0,k.ref=d),g(k))}}function c(a){var b=
null;(a=p(a))&&"OBJECT"==a.nodeName&&("undefined"!=typeof a.SetVariable?b=a:(a=a.getElementsByTagName("object")[0])&&(b=a));return b}function e(){return!K&&t("6.0.65")&&(I.win||I.mac)&&!(I.wk&&312>I.wk)}function f(a,b,c,d){K=!0;E=d||null;Q={success:!1,id:c};var e=p(c);if(e){"OBJECT"==e.nodeName?(H=l(e),S=null):(H=e,S=c);a.id="SWFObjectExprInst";if("undefined"==typeof a.width||!/%$/.test(a.width)&&310>parseInt(a.width,10))a.width="310";if("undefined"==typeof a.height||!/%$/.test(a.height)&&137>parseInt(a.height,
10))a.height="137";w.title=w.title.slice(0,47)+" - Flash Player Installation";d=I.ie&&I.win?"ActiveX":"PlugIn";d="MMredirectURL="+B.location.toString().replace(/&/g,"%26")+"&MMplayerType="+d+"&MMdoctitle="+w.title;b.flashvars="undefined"!=typeof b.flashvars?b.flashvars+("&"+d):d;I.ie&&I.win&&4!=e.readyState&&(d=w.createElement("div"),c+="SWFObjectNew",d.setAttribute("id",c),e.parentNode.insertBefore(d,e),e.style.display="none",function(){4==e.readyState?e.parentNode.removeChild(e):setTimeout(arguments.callee,
10)}());k(a,b,c)}}function h(a){if(I.ie&&I.win&&4!=a.readyState){var b=w.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(l(a),b);a.style.display="none";(function(){4==a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(l(a),a)}function l(a){var b=w.createElement("div");if(I.win&&I.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName("object")[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)1==a[d].nodeType&&
"PARAM"==a[d].nodeName||8==a[d].nodeType||b.appendChild(a[d].cloneNode(!0));return b}function k(a,b,c){var d,e=p(c);if(I.wk&&312>I.wk)return d;if(e)if("undefined"==typeof a.id&&(a.id=c),I.ie&&I.win){var f="",g;for(g in a)a[g]!=Object.prototype[g]&&("data"==g.toLowerCase()?b.movie=a[g]:"styleclass"==g.toLowerCase()?f+=' class="'+a[g]+'"':"classid"!=g.toLowerCase()&&(f+=" "+g+'="'+a[g]+'"'));g="";for(var h in b)b[h]!=Object.prototype[h]&&(g+='<param name="'+h+'" value="'+b[h]+'" />');e.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+
f+">"+g+"</object>";F[F.length]=a.id;d=p(a.id)}else{h=w.createElement("object");h.setAttribute("type","application/x-shockwave-flash");for(var k in a)a[k]!=Object.prototype[k]&&("styleclass"==k.toLowerCase()?h.setAttribute("class",a[k]):"classid"!=k.toLowerCase()&&h.setAttribute(k,a[k]));for(f in b)b[f]!=Object.prototype[f]&&"movie"!=f.toLowerCase()&&(a=h,g=f,k=b[f],c=w.createElement("param"),c.setAttribute("name",g),c.setAttribute("value",k),a.appendChild(c));e.parentNode.replaceChild(h,e);d=h}return d}
function n(a){var b=p(a);b&&"OBJECT"==b.nodeName&&(I.ie&&I.win?(b.style.display="none",function(){if(4==b.readyState){var c=p(a);if(c){for(var d in c)"function"==typeof c[d]&&(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):b.parentNode.removeChild(b))}function p(a){var b=null;try{b=w.getElementById(a)}catch(c){}return b}function q(a,b,c){a.attachEvent(b,c);Z[Z.length]=[a,b,c]}function t(a){var b=I.pv;a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;
a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function D(a,b,c,d){if(!I.ie||!I.mac){var e=w.getElementsByTagName("head")[0];e&&(c=c&&"string"==typeof c?c:"screen",d&&(da=L=null),L&&da==c||(d=w.createElement("style"),d.setAttribute("type","text/css"),d.setAttribute("media",c),L=e.appendChild(d),I.ie&&I.win&&"undefined"!=typeof w.styleSheets&&0<w.styleSheets.length&&(L=w.styleSheets[w.styleSheets.length-1]),da=c),I.ie&&I.win?L&&"object"==
typeof L.addRule&&L.addRule(a,b):L&&"undefined"!=typeof w.createTextNode&&L.appendChild(w.createTextNode(a+" {"+b+"}")))}}function x(a,b){if(N){var c=b?"visible":"hidden";J&&p(a)?p(a).style.visibility=c:D("#"+a,"visibility:"+c)}}function v(a){return null!=/[\\\"<>\.;]/.exec(a)&&"undefined"!=typeof encodeURIComponent?encodeURIComponent(a):a}var B=z,w=document,A=navigator,G=!1,C=[function(){G?b():a()}],P=[],F=[],Z=[],H,S,E,Q,J=!1,K=!1,L,da,N=!0,I=function(){var a="undefined"!=typeof w.getElementById&&
"undefined"!=typeof w.getElementsByTagName&&"undefined"!=typeof w.createElement,b=A.userAgent.toLowerCase(),c=A.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,e=!+"\v1",f=[0,0,0],g=null;if("undefined"!=typeof A.plugins&&"object"==typeof A.plugins["Shockwave Flash"])!(g=A.plugins["Shockwave Flash"].description)||"undefined"!=typeof A.mimeTypes&&A.mimeTypes["application/x-shockwave-flash"]&&
!A.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(G=!0,e=!1,g=g.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),f[0]=parseInt(g.replace(/^(.*)\..*$/,"$1"),10),f[1]=parseInt(g.replace(/^.*\.(.*)\s.*$/,"$1"),10),f[2]=/[a-zA-Z]/.test(g)?parseInt(g.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0);else if("undefined"!=typeof B.ActiveXObject)try{var h=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");h&&(g=h.GetVariable("$version"))&&(e=!0,g=g.split(" ")[1].split(","),f=[parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],
10)])}catch(k){}return{w3:a,pv:f,wk:b,ie:e,win:d,mac:c}}();(function(){I.w3&&(("undefined"!=typeof w.readyState&&"complete"==w.readyState||"undefined"==typeof w.readyState&&(w.getElementsByTagName("body")[0]||w.body))&&d(),J||("undefined"!=typeof w.addEventListener&&w.addEventListener("DOMContentLoaded",d,!1),I.ie&&I.win&&(w.attachEvent("onreadystatechange",function(){"complete"==w.readyState&&(w.detachEvent("onreadystatechange",arguments.callee),d())}),B==top&&function(){if(!J){try{w.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,
0);return}d()}}()),I.wk&&function(){J||(/loaded|complete/.test(w.readyState)?d():setTimeout(arguments.callee,0))}(),m(d)))})();(function(){I.ie&&I.win&&z.attachEvent("onunload",function(){for(var a=Z.length,b=0;b<a;b++)Z[b][0].detachEvent(Z[b][1],Z[b][2]);a=F.length;for(b=0;b<a;b++)n(F[b]);for(var c in I)I[c]=null;I=null;for(var d in r)r[d]=null;r=null})})();return{registerObject:function(a,b,c,d){if(I.w3&&a&&b){var e={};e.id=a;e.swfVersion=b;e.expressInstall=c;e.callbackFn=d;P[P.length]=e;x(a,!1)}else d&&
d({success:!1,id:a})},getObjectById:function(a){if(I.w3)return c(a)},embedSWF:function(a,b,c,d,h,l,n,m,p,q){var r={success:!1,id:b};I.w3&&!(I.wk&&312>I.wk)&&a&&b&&c&&d&&h?(x(b,!1),g(function(){c+="";d+="";var g={};if(p&&"object"===typeof p)for(var v in p)g[v]=p[v];g.data=a;g.width=c;g.height=d;v={};if(m&&"object"===typeof m)for(var w in m)v[w]=m[w];if(n&&"object"===typeof n)for(var z in n)v.flashvars="undefined"!=typeof v.flashvars?v.flashvars+("&"+z+"="+n[z]):z+"="+n[z];if(t(h))w=k(g,v,b),g.id==
b&&x(b,!0),r.success=!0,r.ref=w;else{if(l&&e()){g.data=l;f(g,v,b,q);return}x(b,!0)}q&&q(r)})):q&&q(r)},switchOffAutoHideShow:function(){N=!1},ua:I,getFlashPlayerVersion:function(){return{major:I.pv[0],minor:I.pv[1],release:I.pv[2]}},hasFlashPlayerVersion:t,createSWF:function(a,b,c){return I.w3?k(a,b,c):R},showExpressInstall:function(a,b,c,d){I.w3&&e()&&f(a,b,c,d)},removeSWF:function(a){I.w3&&n(a)},createCSS:function(a,b,c,d){I.w3&&D(a,b,c,d)},addDomLoadEvent:g,addLoadEvent:m,getQueryParamValue:function(a){var b=
w.location.search||w.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(null==a)return v(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return v(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(K){var a=p("SWFObjectExprInst");a&&H&&(a.parentNode.replaceChild(H,a),S&&(x(S,!0),I.ie&&I.win&&(H.style.display="block")),E&&E(Q));K=!1}}}}();return r})})})(function(){var r=window.AmazonUIPageJS||window.P,z=r._namespace||r.attributeErrors;
return z?z("PlatformBooksDetailPageAsset"):r}(),window);
/* ******** */
(function(r,z,R){r.execute(function(){r.when("A","jQuery","atf").execute(function(M,d){M.on.ready(function(){function g(a,b,c,e,f){d(a).slideToggle(300);d(b).slideToggle(300);d(c).toggleClass("tmmShowPrompt tmmHidePrompt");d(e).toggleClass("tmmShowPrompt tmmHidePrompt");d(f).toggleClass("rotate")}function m(a){a.position();a.width();d(".swatchElement");a.find(".swatchElement").each(function(){d(this).attr("data-width",d(this).width())});d("#formats").find(".a-row").removeClass("nonJSFormats")}function b(){var a=
d("#formats"),b=a.width()-40,c=0;a.find(".swatchElement").each(function(){d(this).is(":visible")&&(c+=d(this).width())});c>b?d(a.find(".swatchElement:visible").get().reverse()).each(function(){var a=0,e=!1;d(this).find(".format").hasClass("a-button-selected")?(a=d(this).prev(".swatchElement").width(),e=d(this).prev(".swatchElement").is(":hidden"),d(this).prev(".swatchElement").hide()):(a=d(this).width(),e=d(this).is(":hidden"),d(this).hide());e||(c-=a);return c>b}):c<b&&a.find(".swatchElement").each(function(){if(d(this).is(":hidden"))return d(this).attr("data-width")<=
b-c&&d(this).show(),!1})}var a=0,c=0,e,f=function(a){"undefined"!=typeof a&&(e=new a.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))};"undefined"!=typeof amznJQ?amznJQ.available("DPClientLogger",function(){f(z.DPClientLogger)}):r.when("DPClientLogger").execute(f);M.declarative("tmm-see-more-editions-click",["click"],function(a){var b=a.data,c=b.metabindingUrl;if(a.$target.hasClass("a-link-expander")||a.$target.parent().hasClass("a-link-expander")){var b=b.metabindingPlaceHolder,e="#metabinding_row_top_"+
b,f="#metabinding_row_bottom_"+b,h="#editionsSeePrompt_"+b,l="#editionsHidePrompt_"+b,m="#editionsIcon_"+b,r="isAjaxComplete_"+b,w="isAjaxInProgress_"+b;a="#tmmSpinnerDiv_"+b;var A=M.state("mediamatrix-state"),b=A["url_"+b].replace(/&amp;/g,"&");d("#formats .tmmErrorClass").hide();"1"===A[r]||"1"===A[w]?g(e,f,h,l,m):(M.ajax(b,{method:"get",success:function(){A[r]="1";M.state("mediamatrix-state",A);g(e,f,h,l,m)},indicator:d(a),error:function(){d($tmmErrorDiv).show();A[w]="0";M.state("mediamatrix-state",
A)}}),A[w]="1",M.state("mediamatrix-state",A))}else"#"!==c&&(z.location=c)});if(0<d("#formats > .a-link-expander").length){var h=z.ue;h&&h.count&&h.count("mediaMatrixExpanderPresent",1)}d("#formats > .a-link-expander").click(function(){g("#tmmSwatches","#twister","#showMoreFormatsPrompt","#hideMoreFormatsPrompt","#formatsIcon");if(!c){var b=z.ue;b&&b.count&&b.count("mediaMatrixExpanderClicked",1);c=1}e&&d("#twister").is(":visible")&&!a&&(e.logImpression("tmm-show-more-formats-viewed"),a=1)});d("#formats.responsive").each(function(){m(d(this))});
var h=M.state("mediamatrixState"),l="false";"undefined"!==typeof h&&"undefined"!==typeof h.swatchWrap&&(l=h.swatchWrap);"true"!=l&&(b(),M.on("resize",b));d("#formats .unselected .format").mouseenter(function(){d(this).find(".a-color-secondary").addClass("a-color-price").removeClass("a-color-secondary")}).mouseleave(function(){d(this).find(".a-color-price").addClass("a-color-secondary").removeClass("a-color-price")});d("#landingItemRentalLink").attr("href","javascript:document.getElementById('rentBuySection').click();")})})})})(function(){var r=
window.AmazonUIPageJS||window.P,z=r._namespace||r.attributeErrors;return z?z("TwisterBooksDetailPageAsset"):r}(),window);
/* ******** */
(function(c){c.execute(function(){})})(function(){var c=window.AmazonUIPageJS||window.P,e=c._namespace||c.attributeErrors;return e?e("DetailPageBookProductDescriptionAssets"):c}(),window);
/* ******** */
